services:
  - type: web
    name: small-wedding
    runtime: node
    plan: free
    buildCommand: npm install --prefix backend && npm install --prefix frontend && npm run build --prefix frontend
    startCommand: npm start --prefix backend
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
      - key: RSVP_EMAIL_TO
        value: adrian.plapamaru@gmail.com
      - key: WEB3FORMS_ACCESS_KEY_LOCAL
        sync: false
      - key: WEB3FORMS_ACCESS_KEY_RENDER
        sync: false
